package com.br.helpcenter.view;
import com.br.helpcenter.bean.ClienteBean;
import com.br.helpcenter.controller.ClienteController;
import com.br.helpcenter.util.ValidationUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author mauriciods
 */
public class FormCliente extends javax.swing.JFrame {
    private int id;
    private Principal p;
    private OS os;
    private int cpfVazio = 0;
    private int foneVazio = 0;
    private int emailVazio = 0;
    /**
     * Creates new form CadCli
     */
    //recebe cliente para alterar
    public FormCliente(ClienteBean cb1) {
        initComponents();
        btnCad.setEnabled(false);
        this.id = cb1.getId();
        txtNome.setText(cb1.getNome());
        txtCel.setText(cb1.getFoneUm());
        txtFone.setText(cb1.getFoneDois());
        txtEmai.setText(cb1.getEmail());
        txtEnd.setText(cb1.getEndereco());
        setTitle("Alterar Cliente");
    }
    //inicia tela no modo cadastro
    public FormCliente() {
        initComponents();
        btnAlt.setEnabled(false);
    }
    //recebe objeto tela princiapal para cadastrar novo cliente e inserir no combo da tela principal
    public FormCliente(Principal p) {
        initComponents();
        this.p = p;
        btnAlt.setEnabled(false);
    }
    //recebe objeto tela de os para cadastrar novo cliente e inserir no combo da tela principal
    FormCliente(OS os) {
        initComponents();
        this.os = os;
        btnAlt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        txtCel = new javax.swing.JFormattedTextField();
        txtFone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        checkVazioCPF = new javax.swing.JCheckBox();
        checkVazioTel = new javax.swing.JCheckBox();
        checkEMailVazio = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnCad = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome:");

        jLabel2.setText("Celular:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("E-mail:");

        jLabel5.setText("Endereço:");

        try {
            txtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        checkVazioCPF.setText("Vazio");
        checkVazioCPF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkVazioCPFStateChanged(evt);
            }
        });

        checkVazioTel.setText("Vazio");
        checkVazioTel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkVazioTelStateChanged(evt);
            }
        });

        checkEMailVazio.setText("Vazio");
        checkEMailVazio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkEMailVazioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmai)
                    .addComponent(txtNome)
                    .addComponent(txtEnd)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkVazioTel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkEMailVazio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkVazioCPF)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(checkVazioTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkEMailVazio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkVazioCPF))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/add_blue_32.png"))); // NOI18N
        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        jPanel2.add(btnCad);

        btnLim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/cancel.png"))); // NOI18N
        btnLim.setText("Limpar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        jPanel2.add(btnLim);

        btnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/document-edit_yellow_32.png"))); // NOI18N
        btnAlt.setText("Editar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        ClienteBean cb1 = new ClienteBean();
        ValidationUtil vu = new ValidationUtil();
        cb1.setNome(txtNome.getText());
        cb1.setFoneUm(txtCel.getText());
        //verifica se campos estao vazios e insere String em branco caso estiverem
        if(foneVazio == 0) {
            cb1.setFoneDois(txtFone.getText());
        } else {
            cb1.setFoneDois("");
        }
        if(emailVazio == 0) {
            cb1.setEmail(txtEmai.getText());
        } else {
            cb1.setEmail("");
        }
        cb1.setEndereco(txtEnd.getText());
        if(cpfVazio == 0) {
            cb1.setCPF(txtCPF.getText());
        } else {
            cb1.setCPF("");
        }
        //-----------------------------------------------------------------------
        if (ClienteController.create(cb1) > 0) {
            JOptionPane.showMessageDialog(null, "Registro inserido!");
            if(p!=null){
                //atualiza combo da tela principal
                p.carregaComboBox("Todos");   
            }
            if(os!=null){
                //atualiza combo da tela de os
                os.carregaComboBox("Todos");
            }
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        //altera informações de cliente
        ClienteBean cb1 = new ClienteBean();
        ValidationUtil vu = new ValidationUtil();
        cb1.setId(id);
        cb1.setNome(txtNome.getText());
        cb1.setFoneUm(vu.removeMaskTel(txtCel.getText()));
        cb1.setFoneDois(vu.removeMaskTel(txtFone.getText()));
        cb1.setEmail(txtEmai.getText());
        cb1.setEndereco(txtEnd.getText());
        if (ClienteController.update(cb1) > 0) {
            JOptionPane.showMessageDialog(null, "Registro atualizado!");
        }
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        //limpa campos
        txtNome.setText("");
        txtCel.setText("");
        txtFone.setText("");
        txtEmai.setText("");
        txtEnd.setText("");
        txtCPF.setText("");
    }//GEN-LAST:event_btnLimActionPerformed
    //checkbox de verificacao se cpf vai ficar vazio
    private void checkVazioCPFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkVazioCPFStateChanged
        if(checkVazioCPF.isSelected()) {
           cpfVazio = 1;
           txtCPF.setEnabled(false);
        } else {
            cpfVazio = 0;
            txtCPF.setEnabled(true);
        }
        
    }//GEN-LAST:event_checkVazioCPFStateChanged
    //checkbox de verificacao se telefone vai ficar vazio
    private void checkVazioTelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkVazioTelStateChanged
        if(checkVazioTel.isSelected()) {
            txtFone.setEnabled(false);
            foneVazio = 1;
        } else {
            txtFone.setEnabled(true);
            foneVazio = 0;
        }
    }//GEN-LAST:event_checkVazioTelStateChanged
    //checkbox de verificacao se e-mail vai ficar vazio
    private void checkEMailVazioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkEMailVazioStateChanged
        if(checkEMailVazio.isSelected()) {
            txtEmai.setEnabled(false);
            emailVazio = 1;
        } else {
            txtEmai.setEnabled(true);
            emailVazio = 0;
        }
    }//GEN-LAST:event_checkEMailVazioStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnLim;
    private javax.swing.JCheckBox checkEMailVazio;
    private javax.swing.JCheckBox checkVazioCPF;
    private javax.swing.JCheckBox checkVazioTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCel;
    private javax.swing.JTextField txtEmai;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JFormattedTextField txtFone;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
