/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.helpcenter.view;

import com.br.helpcenter.bean.ClienteBean;
import com.br.helpcenter.bean.OSBean;
import com.br.helpcenter.controller.ClienteController;
import com.br.helpcenter.controller.OSController;
import com.br.helpcenter.util.ManipulaDataHora;
import java.math.BigDecimal;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import com.br.helpcenter.util.ValidationUtil;

/**
 *
 * @author mauriciods
 */
public class OS extends javax.swing.JFrame {
    private Timer timer = new Timer();
    private int tipoOS = 0;
    private OSBean ob;
    private OSRel osRel;
    /**
     * Creates new form OS
     */
    public OS() {
        initComponents();
        setTitle("Cadastrar OS");
        carregaComboBox("Todos");
        btnAlt.setEnabled(false);
        ManipulaDataHora mdh = new ManipulaDataHora();
        int tempo = 1000;
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String dataBr = mdh.getDataHoraBR();
                txtDataHora.setText(dataBr);
            }
        }, tempo, tempo);
    }
    
    OS(ClienteBean cb1) {
        initComponents();
        setTitle("Cadastrar OS");
        btnAlt.setEnabled(false);
        txtCli.addItem(cb1.getNome(), cb1);
        ManipulaDataHora mdh = new ManipulaDataHora(); 
        int tempo = 1000;
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String dataBr = mdh.getDataHoraBR();
                txtDataHora.setText(dataBr);
            }
        }, tempo, tempo);
    }

    OS(OSBean ob, OSRel osRel) {
        initComponents();
        setTitle("Alterar OS");
        this.ob = ob;
        this.osRel = osRel;
        btnCad.setEnabled(false);
        txtNumOS.setText(String.valueOf(ob.getNumero()));
        cbSitu.setSelectedItem(ob.getSituacao());
        if(ob.getTipoOSRet().equals("Orçamento")) {
            buttonGroup1.setSelected(rdOc.getModel(), true);
            tipoOS = 1;
        } else {
            buttonGroup1.setSelected(rdOS.getModel(), true);
            tipoOS = 2;
        }
        txtDHOS.setText(ob.getDataOS());
        txtCli.addItem(ob.getClienome(), ob);
        txtEquip.setText(ob.getEquipamento());
        txtDef.setText(ob.getDefeito());
        txtServ.setText(ob.getServico());
        txtVlr.setText(String.valueOf(ob.getValor()));
        
        ManipulaDataHora mdh = new ManipulaDataHora();
        int tempo = 1000;
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String dataBr = mdh.getDataHoraBR();
                txtDataHora.setText(dataBr);
            }
        }, tempo, tempo);
    }

    public void carregaComboBox(String nome) {
        txtCli.clear();
        for (ClienteBean cb : ClienteController.read(nome)) {
            txtCli.addItem(cb.getNome(), cb);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDataHora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumOS = new javax.swing.JTextField();
        rdOc = new javax.swing.JRadioButton();
        rdOS = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbSitu = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtDHOS = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEquip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDef = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtVlr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtServ = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnCad = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCli = new componentes.UJComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        itMenCadCli = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/Config-Tools.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/config-tools-58.png"))); // NOI18N
        jLabel11.setText("Ordem de Serviço");

        txtDataHora.setEditable(false);

        jLabel2.setText("Data/Hora:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataHora)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtDataHora)
                        .addComponent(jLabel2))
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nº OS:");

        txtNumOS.setEditable(false);
        txtNumOS.setEnabled(false);

        buttonGroup1.add(rdOc);
        rdOc.setText("Orçamento");
        rdOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOcActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdOS);
        rdOS.setText("Ordem de serviço");
        rdOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOSActionPerformed(evt);
            }
        });

        jLabel3.setText("Situação:");

        cbSitu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega OK", "Orçamento REPROVADO", "Aguardando aprovação", "Aguardando peças", "Abandonado pelo cliente", "Na bancada", "Retornou", "Orçamento APROVADO", " " }));

        jLabel12.setText("Data/Hora OS:");

        txtDHOS.setEditable(false);
        txtDHOS.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdOc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdOS))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumOS)
                            .addComponent(cbSitu, 0, 263, Short.MAX_VALUE)
                            .addComponent(txtDHOS))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumOS))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDHOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbSitu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdOc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("* Campos obrigatórios"));

        jLabel5.setText("* Equipamento:");

        txtEquip.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jLabel6.setText("* Defeito:");

        txtDef.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jLabel8.setText("Valor:");

        txtVlr.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txtVlr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVlrKeyReleased(evt);
            }
        });

        jLabel7.setText("* Serviço:");

        txtServ.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEquip)
                    .addComponent(txtDef)
                    .addComponent(txtServ)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txtVlr, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVlr)
                .addGap(24, 24, 24))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/add_blue_32.png"))); // NOI18N
        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        jPanel5.add(btnCad);

        btnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/document-edit_yellow_32.png"))); // NOI18N
        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        jPanel5.add(btnAlt);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/NF_32.png"))); // NOI18N
        jButton3.setText("Gerar nota fiscal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/user-64.png"))); // NOI18N

        txtCli.setEditable(true);
        txtCli.setAutocompletar(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        menCad.setText("Cadastrar");

        itMenCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        itMenCadCli.setText("Cliente");
        itMenCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenCadCliActionPerformed(evt);
            }
        });
        menCad.add(itMenCadCli);

        jMenuBar1.add(menCad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        timer.cancel();
    }//GEN-LAST:event_formWindowClosed

    private void itMenCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenCadCliActionPerformed
        FormCliente formCli = new FormCliente(this);
        formCli.setVisible(true);
    }//GEN-LAST:event_itMenCadCliActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "Deseja emitir nota fiscal?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Clique no botão \"Gerar nota "
                    + "fiscal\" para emitir a nota e cadastrar a Ordem de Serviço.", 
                    "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if(!txtEquip.getText().equals("") && !txtDef.equals("") && !txtServ.getText().equals("") && tipoOS != 0) {
                   ClienteBean cb1 = (ClienteBean) txtCli.getSelectedObject();
                   int idcliente = 0;
                   idcliente = cb1.getId();
                if (idcliente == 0) {
                    JOptionPane.showMessageDialog(null, "Selecione o cliente.", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    OSBean ob1 = new OSBean();
                    ManipulaDataHora mdh = new ManipulaDataHora();
                    ob1.setIdcliente(cb1.getId());
                    ob1.setTipo(tipoOS);
                    ob1.setSituacao((String) cbSitu.getSelectedItem());
                    ob1.setEquipamento(txtEquip.getText());
                    ob1.setDefeito(txtDef.getText());
                    ob1.setServico(txtServ.getText());
                    if (txtVlr.getText().isEmpty()){
                       ob1.setValor(new BigDecimal("0.00")); 
                    } else {
                        ValidationUtil vu = new ValidationUtil();
                        ob1.setValor(new BigDecimal(vu.validaPreco(txtVlr.getText())));
                    }
                    System.out.print("ID: "+cb1.getId());
                    System.out.println("Nome: "+cb1.getNome());
                    ob1.setTemntos("N");
                    /*if (OSController.create(ob) > 0) {
                        JOptionPane.showMessageDialog(null, "OS Cadastrada com sucesso.", "Registro inserido.",JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Confira as informações inseridas.", "Atenção",JOptionPane.WARNING_MESSAGE);
                    }*/
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.","Campos em branco.",JOptionPane.WARNING_MESSAGE);
            }
          }
        
    }//GEN-LAST:event_btnCadActionPerformed

    private void rdOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOSActionPerformed
        tipoOS = 2;
    }//GEN-LAST:event_rdOSActionPerformed

    private void rdOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOcActionPerformed
        tipoOS = 1;
    }//GEN-LAST:event_rdOcActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        OSBean ob1 = new OSBean();
        ManipulaDataHora mdh = new ManipulaDataHora();
        ob1.setNumero(ob.getNumero());
        ob1.setDataOS(mdh.getDataHoraUS(ob.getDataOS()));
        ob1.setSituacao((String) cbSitu.getSelectedItem());
        ob1.setTipo(tipoOS);
        ob1.setIdcliente(ob.getIdcliente());
        ob1.setEquipamento(txtEquip.getText());
        ob1.setDefeito(txtDef.getText());
        ob1.setServico(txtServ.getText());
        ValidationUtil vu = new ValidationUtil();
        ob1.setValor(new BigDecimal(vu.validaPreco(txtVlr.getText())));
        if (OSController.update(ob1) > 0) {
            osRel.populaTabOSRel();
            JOptionPane.showMessageDialog(null, "OS alterada");
        }
    }//GEN-LAST:event_btnAltActionPerformed

    private void txtVlrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVlrKeyReleased
        String valorOS = txtVlr.getText();
        ValidationUtil vu = new ValidationUtil();
        String valor = vu.formatMoney(valorOS);
        if(valor != null){
            txtVlr.setText(valor);
        }
    }//GEN-LAST:event_txtVlrKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSitu;
    private javax.swing.JMenuItem itMenCadCli;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu menCad;
    private javax.swing.JRadioButton rdOS;
    private javax.swing.JRadioButton rdOc;
    private componentes.UJComboBox txtCli;
    private javax.swing.JTextField txtDHOS;
    private javax.swing.JTextField txtDataHora;
    private javax.swing.JTextField txtDef;
    private javax.swing.JTextField txtEquip;
    private javax.swing.JTextField txtNumOS;
    private javax.swing.JTextField txtServ;
    private javax.swing.JTextField txtVlr;
    // End of variables declaration//GEN-END:variables
}
