/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.helpcenter.view;

import com.br.helpcenter.bean.OSBean;
import com.br.helpcenter.controller.OSRelController;
import com.br.helpcenter.model.OSRelTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mauriciods
 */
public class OSRel extends javax.swing.JFrame {
    private TableRowSorter<TableModel> sorter;
    private OSRelTableModel osRelTableModel = new OSRelTableModel();
    private List<OSBean> osS;
    //private int qtd;
    private OSBean ob;
    private NotaOS ntOs;
    /**
     * Creates new form OSRel
     */
    public OSRel() {
        initComponents();
        populaTabOSRel();
        btnAdd.setEnabled(false);
    }

    OSRel(NotaOS ntOs) {//recebe objeto NotaOS para atualizar informacoes no outro Frame
        initComponents();
        populaTabOSRel();
        btnAdd.setEnabled(true);
        btnNotaOS.setEnabled(false);
        //this.osS = osS;
        //this.qtd = qtd;
        //this.ob = ob;
        this.ntOs = ntOs;
    }
    //consulta todas os OSs
    protected void populaTabOSRel() {
        osS = OSRelController.read(); //adiciona todas as OSs ao list global de osS
                                      //para trabalhar com a filtragem nos eventos de ItemStateChanged dos radios buttons 
        osRelTableModel.addListaOS(osS); //adiciona todas as OSs no table model
        tabOSRel.setModel(osRelTableModel);
        sorter = new TableRowSorter<TableModel>(osRelTableModel); //permite a filtragem das linhas
        tabOSRel.setRowSorter(sorter); //seta RowSorter
        tabOSRel.getColumnModel().getColumn(0).setMinWidth(0); //oculta coluna 0 da Jtable
        tabOSRel.getColumnModel().getColumn(0).setMaxWidth(0); //oculta coluna 0 da Jtable
        tabOSRel.getColumnModel().getColumn(10).setMinWidth(0); //oculta coluna 10 da Jtable
        tabOSRel.getColumnModel().getColumn(10).setMaxWidth(0); //oculta coluna 10 da Jtable
    }
    //consulta OSs de acordo com periodo selecionado
    protected void populaTabOSRel(String dtIni, String dtFin, String notaOS) {
        if(!OSRelController.read(dtIni, dtFin, notaOS).isEmpty()) {//verifica se nao esta vazio
            osRelTableModel.addListaOS(OSRelController.read(dtIni, dtFin, notaOS)); //adiciona lista de OSs
            tabOSRel.setRowSorter(sorter); //permite a filtragem das linhas da tabela
        }
    }
    //exibe OSs de acordo com o marcado no radio button
    private void populaTabOSRel(List<OSBean> oSs) {
        osRelTableModel.addListaOS(oSs);
        TableModel tbModel = osRelTableModel;
        tabOSRel.setModel(tbModel);
        sorter = new TableRowSorter<TableModel>(tbModel);
        tabOSRel.setRowSorter(sorter);
        tabOSRel.getColumnModel().getColumn(0).setMinWidth(0);
        tabOSRel.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabOSRel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAlt = new javax.swing.JButton();
        btnNotaOS = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();
        lblTxtPesq = new javax.swing.JLabel();
        lblPesq = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        menFiltrar = new javax.swing.JMenu();
        menDat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabOSRel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabOSRel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/document-edit_yellow_32.png"))); // NOI18N
        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlt);

        btnNotaOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/config-tools-32.png"))); // NOI18N
        btnNotaOS.setText("Nota OS");
        btnNotaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaOSActionPerformed(evt);
            }
        });
        jPanel2.add(btnNotaOS);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/shopping-cart_blue_32.png"))); // NOI18N
        btnAdd.setText("Adicionar a Nota");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/config-tools-58.png"))); // NOI18N
        jLabel1.setText("Relatório de OS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });

        lblTxtPesq.setText("Pesquisar:");

        lblPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/search_blue_32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTxtPesq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesq)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtPesq)
                    .addComponent(lblPesq))
                .addContainerGap())
        );

        menFiltrar.setText("Filtrar");

        menDat.setText("Data");
        menDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDatActionPerformed(evt);
            }
        });
        menFiltrar.add(menDat);

        jMenuBar.add(menFiltrar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
         String pesquisa = txtPesq.getText();
        try {
            sorter.setRowFilter(RowFilter.regexFilter(pesquisa));
        } catch (PatternSyntaxException pse) {
                System.err.println(pse);
            }
    }//GEN-LAST:event_txtPesqKeyReleased

    private void btnNotaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaOSActionPerformed
       int linha = tabOSRel.getSelectedRow();
       if (linha != -1) {
           int id = (int) tabOSRel.getValueAt(tabOSRel.getSelectedRow(), 0); 
           OSBean ob1 = osRelTableModel.getLinhas().get(id);
           ntOs = new NotaOS();
           ntOs.adicionaOS(ob1);
           ntOs.setVisible(true);
       }
    }//GEN-LAST:event_btnNotaOSActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       int linha = tabOSRel.getSelectedRow();
       if (linha != -1) {
           int id = (int) tabOSRel.getValueAt(tabOSRel.getSelectedRow(), 0); 
           OSBean ob1 = osRelTableModel.getLinhas().get(id);    
           if(ntOs.idos != ob1.getNumero()) {
               this.dispose();
               ntOs.adicionaOS(ob1);
               ntOs.setVisible(true);
           } else {
               JOptionPane.showMessageDialog(null, "Item já adicionado!", "Atenção", JOptionPane.WARNING_MESSAGE);
           }
       }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        int id = (int) tabOSRel.getValueAt(tabOSRel.getSelectedRow(), 0);
        OSBean obAlt = osRelTableModel.getLinhas().get(id);
        OS os = new OS(obAlt, this);
        os.setVisible(true);
    }//GEN-LAST:event_btnAltActionPerformed

    private void menDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDatActionPerformed
        OSRelData osRelData = new OSRelData(this);
        osRelData.setVisible(true);
    }//GEN-LAST:event_menDatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OSRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OSRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OSRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OSRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OSRel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnNotaOS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesq;
    private javax.swing.JLabel lblTxtPesq;
    private javax.swing.JMenuItem menDat;
    private javax.swing.JMenu menFiltrar;
    private javax.swing.JTable tabOSRel;
    private javax.swing.JTextField txtPesq;
    // End of variables declaration//GEN-END:variables
}
