/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.helpcenter.view;

import com.br.helpcenter.bean.CabNoBean;
import com.br.helpcenter.bean.ClienteBean;
import com.br.helpcenter.bean.ProdutoBean;
import com.br.helpcenter.controller.CabNoController;
import com.br.helpcenter.controller.ClienteController;
import com.br.helpcenter.controller.ProdutoController;
import com.br.helpcenter.model.ProdutoTableModel;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
/**
 *
 * @author mauriciods
 */
public class Principal extends javax.swing.JFrame {
    private ProdutoTableModel ptm = new ProdutoTableModel();
    
    public Principal() {
        initComponents();
        tabItens.setModel(ptm); //seta o ProdutoTableModel (variavel ptm) na tabela de itens
        carregaComboBox("Todos"); //lista todos os clientes no combobox de cliente
    }   
    
    Principal(CabNoBean cnb) { //ao acionar esse construtor exibe na tela a nota selecionada na tela anterior
        initComponents();
        lblQtd.setText("Qtd. Total"); //troca texto da jLabel de Quantidade
        btnEncerrar.setEnabled(false); //desabilita o botao encerrar
        btnRemItem.setEnabled(false); //desabilita o botao remover item
        btnCan.setEnabled(false); //desabilita o botao cancelar
        tabItens.setModel(ptm); // seta o ProdutoTableModel (variavel ptm) na tabela de itens
        txtCli.addItem(cnb.getClienNome(), cnb); //adiciona o cliente no combobox cliente
        txtTot.setText(String.valueOf(cnb.getTotalCabNota())); //mostrar valor total da nota
        txtQuant.setText(String.valueOf(cnb.getQuantidade()));
        ptm.addListaDeProdutos(cnb.getItens()); //adiciona os produtos na tabela
    }

    Principal(ClienteBean cb1) {//ao acionar esse construtor o combobox cliente recebe o nome do proximo cliente
        initComponents();
        tabItens.setModel(ptm);
        txtCli.addItem(cb1.getNome(), cb1);
    }
    
    public void carregaComboBox(String nome) { //metodo responsavel por popular combobox de clientes
        txtCli.clear();
        for (ClienteBean cb : ClienteController.read(nome)) {
            txtCli.addItem(cb.getNome(), cb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEAN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProd = new javax.swing.JTextField();
        lblQtd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVlr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        txtQuant = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabItens = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnEncerrar = new javax.swing.JButton();
        btnRemItem = new javax.swing.JButton();
        btnCan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtMens = new javax.swing.JTextField();
        jPLogo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCli = new componentes.UJComboBox();
        barraMenu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        cadCli = new javax.swing.JMenuItem();
        cadProd = new javax.swing.JMenuItem();
        cadOS = new javax.swing.JMenuItem();
        cadRegMov = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        itemMenCli = new javax.swing.JMenuItem();
        itemMenProd = new javax.swing.JMenuItem();
        itemMenOS = new javax.swing.JMenuItem();
        itemMenMov = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        itemMenOSRel = new javax.swing.JMenuItem();
        ItemMenVendRel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HelpCenter ERP");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setText("EAN:");

        txtEAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEANKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Produto:");

        lblQtd.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblQtd.setText("Quantidade:");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setText("Valor unitário:");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setText("Dinheiro:");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setText("Troco:");

        txtQuant.setText("1");
        txtQuant.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(202, 202, 202))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtQuant)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(txtVlr))))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(txtProd)
                    .addComponent(txtEAN)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEAN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVlr)
                    .addComponent(txtQuant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabItens);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/shopping-cart_blue_32.png"))); // NOI18N
        jButton1.setText("Nova venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        btnEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/button-check_green_32.png"))); // NOI18N
        btnEncerrar.setText("Encerrar");
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEncerrar);

        btnRemItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/trash-empty.png"))); // NOI18N
        btnRemItem.setText("Remover item");
        btnRemItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemItemActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemItem);

        btnCan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/cancel.png"))); // NOI18N
        btnCan.setText("Cancelar");
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });
        jPanel3.add(btnCan);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel8.setText("Total geral:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTot)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTot)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel7.setText("Mensagens:");

        txtMens.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMens)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMens)
                .addContainerGap())
        );

        jPLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPLogoLayout = new javax.swing.GroupLayout(jPLogo);
        jPLogo.setLayout(jPLogoLayout);
        jPLogoLayout.setHorizontalGroup(
            jPLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPLogoLayout.setVerticalGroup(
            jPLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 20)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/user-64.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 20)); // NOI18N
        jLabel10.setText("Cliente");

        txtCli.setAutocompletar(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addComponent(txtCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menCad.setText("Cadastro");

        cadCli.setText("Cliente");
        cadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCliActionPerformed(evt);
            }
        });
        menCad.add(cadCli);

        cadProd.setText("Produto");
        cadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProdActionPerformed(evt);
            }
        });
        menCad.add(cadProd);

        cadOS.setText("OS");
        cadOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadOSActionPerformed(evt);
            }
        });
        menCad.add(cadOS);

        cadRegMov.setText("Registro de movimento");
        cadRegMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadRegMovActionPerformed(evt);
            }
        });
        menCad.add(cadRegMov);

        barraMenu.add(menCad);

        menOpc.setText("Opções");

        itemMenCli.setText("Clientes");
        itemMenCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenCliActionPerformed(evt);
            }
        });
        menOpc.add(itemMenCli);

        itemMenProd.setText("Produtos");
        itemMenProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenProdActionPerformed(evt);
            }
        });
        menOpc.add(itemMenProd);

        itemMenOS.setText("OS");
        itemMenOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenOSActionPerformed(evt);
            }
        });
        menOpc.add(itemMenOS);

        itemMenMov.setText("Movimentos");
        itemMenMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenMovActionPerformed(evt);
            }
        });
        menOpc.add(itemMenMov);

        barraMenu.add(menOpc);

        menRel.setText("Relatório");

        itemMenOSRel.setText("OS");
        itemMenOSRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenOSRelActionPerformed(evt);
            }
        });
        menRel.add(itemMenOSRel);

        ItemMenVendRel.setText("Vendas");
        ItemMenVendRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenVendRelActionPerformed(evt);
            }
        });
        menRel.add(ItemMenVendRel);

        barraMenu.add(menRel);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(810, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //aciona form para cadastro de clientes
    private void cadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCliActionPerformed
        FormCliente fc = new FormCliente(this);
        fc.setVisible(true);
    }//GEN-LAST:event_cadCliActionPerformed
    //aciona tela responsavel pela manutencao do cadastro de clientes
    private void itemMenCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenCliActionPerformed
        Cliente c = new Cliente();
        c.setVisible(true);
    }//GEN-LAST:event_itemMenCliActionPerformed
    //aciona form responsavel pela manutencao do cadastro de produtos
    private void itemMenProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenProdActionPerformed
        Produto p = new Produto();
        p.setVisible(true);
    }//GEN-LAST:event_itemMenProdActionPerformed
    //aciona form responsavel pelo cadastro de produtos
    private void cadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProdActionPerformed
        FormProduto fp = new FormProduto();
        fp.setVisible(true);
    }//GEN-LAST:event_cadProdActionPerformed
    //aciona form responsavel pelo relatorio de os
    private void itemMenOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenOSActionPerformed
        OSRel OSR = new OSRel();
        OSR.setVisible(true);
    }//GEN-LAST:event_itemMenOSActionPerformed
    //evento responsavel por encontrar produto ao pressionar enter
    private void txtEANKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEANKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           if (txtQuant.getText().equals("")) {
                txtMens.setText("Informe a quantidade!");
           } else {
                ProdutoBean pb = ProdutoController.searchProduEAN(txtEAN.getText());
                if(pb.getDesc().equals("vazio") == false){
                       txtProd.setText(pb.getDesc());
                       txtVlr.setText(pb.getPreco().toString());
                       pb.setQtd(Integer.valueOf(txtQuant.getText()));
                       ptm.addRow(pb);
                       BigDecimal total = new BigDecimal("0");
                       for (ProdutoBean pbtotal : ptm.getLinhas()){
                            BigDecimal temp = new BigDecimal(pbtotal.getQtd());
                            BigDecimal totalprod = pbtotal.getPreco().multiply(temp);
                            total = total.add(totalprod);
                        }
                       txtTot.setText(String.valueOf(total));
                   }
                }
       }
    }//GEN-LAST:event_txtEANKeyPressed
    //evento responsavel por encerrar venda ao clicar no botao encerrar
    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        BigDecimal total = new BigDecimal("0"); //inicializa variaveis
        int quantidade = 0;
        if (!ptm.getLinhas().isEmpty()) { //se a tabela nao estiver vazia inicia registro de venda
            for (ProdutoBean pb : ptm.getLinhas()){ //passa linha por linha multiplicando preco produto pela quantidade vendida
                BigDecimal temp = new BigDecimal(pb.getQtd());
                BigDecimal totalprod = pb.getPreco().multiply(temp);
                total = total.add(totalprod);
                quantidade = quantidade + pb.getQtd(); //soma quantidade total de produtos
            }
            CabNoBean cnb = new CabNoBean(); //cria objeto cabecalho da nota
            ClienteBean cb1 = (ClienteBean) txtCli.getSelectedObject();
            cnb.setIdCliente(cb1.getId());
            cnb.setQuantidade(quantidade);
            cnb.setTotalCabNota(total);
            cnb.seteOSCabNota("N"); //identifica que nao e uma nota de os
            cnb.setItens(ptm.getLinhas()); //armazna itens da venda no objeto
            int inserido = CabNoController.create(cnb); //persisti objeto na base de dados
            
            if (inserido > 0) { //verifica se produto foi inserido caso contrario exibe mensagem de erro
                txtMens.setText("Venda efetuada!");
                ptm.getLinhas().clear();
            } else {
                txtMens.setText("Atenção o carrinho está vazio!");
            }
        }
    }//GEN-LAST:event_btnEncerrarActionPerformed
    //evento responsavel por remover linha ao clicar no botao remover
    private void btnRemItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemItemActionPerformed
        int linha = tabItens.getSelectedRow();
        if (linha != -1) {
            ptm.removeRow(linha);
        }
    }//GEN-LAST:event_btnRemItemActionPerformed
    //evento responsavel por carregar tela de registro de movimentacao
    private void cadRegMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadRegMovActionPerformed
        Movimento mov = new Movimento();
        mov.setVisible(true);
    }//GEN-LAST:event_cadRegMovActionPerformed
    //evento responsavel por carregar tela de movimentacao
    private void itemMenMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenMovActionPerformed
        Movimento mov = new Movimento();
        mov.setVisible(true);
    }//GEN-LAST:event_itemMenMovActionPerformed
    //evento responsavel por carregar tela de cadastro de os
    private void cadOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadOSActionPerformed
        OS os = new OS();
        os.setVisible(true);
    }//GEN-LAST:event_cadOSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    //evento responsavel por acionar tela de relatorio de os
    private void itemMenOSRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenOSRelActionPerformed
        OSRel osr = new OSRel();
        osr.setVisible(true);
    }//GEN-LAST:event_itemMenOSRelActionPerformed
    //ecento responsavel por acionar tela de relatorio de vendas
    private void ItemMenVendRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenVendRelActionPerformed
        VendaRel vr = new VendaRel();
        vr.setVisible(true);
    }//GEN-LAST:event_ItemMenVendRelActionPerformed

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenVendRel;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnCan;
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JButton btnRemItem;
    private javax.swing.JMenuItem cadCli;
    private javax.swing.JMenuItem cadOS;
    private javax.swing.JMenuItem cadProd;
    private javax.swing.JMenuItem cadRegMov;
    private javax.swing.JMenuItem itemMenCli;
    private javax.swing.JMenuItem itemMenMov;
    private javax.swing.JMenuItem itemMenOS;
    private javax.swing.JMenuItem itemMenOSRel;
    private javax.swing.JMenuItem itemMenProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenu menRel;
    private javax.swing.JTable tabItens;
    private componentes.UJComboBox txtCli;
    private javax.swing.JTextField txtEAN;
    private javax.swing.JTextField txtMens;
    private javax.swing.JTextField txtProd;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtVlr;
    // End of variables declaration//GEN-END:variables
}
