/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.helpcenter.view;

import com.br.helpcenter.bean.CabNoBean;
import com.br.helpcenter.controller.VendaRelController;
import com.br.helpcenter.model.VendaRelTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mauriciods
 */
public class VendaRel extends javax.swing.JFrame {
    VendaRelTableModel vrt = new VendaRelTableModel();
    int modoTela;
    /**
     * Creates new form VendaRel
     */
    public VendaRel() {
        initComponents();
        //parametro 1 retorna lista de vendas
        rdVend.setSelected(true);
        modoTela = 1;
        vrt.addListaDeVendas(VendaRelController.read(1));
        tabVend.setModel(vrt);
        tabVend.getColumnModel().getColumn(0).setMinWidth(0); //oculta coluna 0 da Jtable
        tabVend.getColumnModel().getColumn(0).setMaxWidth(0); //oculta coluna 0 da Jtable
    }
    
    public void populaVendaRel(String dtIni, String dtFin, int modoTela) {
        if(!VendaRelController.read(dtIni, dtFin, modoTela).isEmpty()) {
            vrt.addListaDeVendas(VendaRelController.read(dtIni, dtFin, modoTela));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblModo = new javax.swing.JLabel();
        rdVend = new javax.swing.JRadioButton();
        rdManut = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVend = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        menFiltrar = new javax.swing.JMenu();
        menDat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/shopping-cart_blue.png"))); // NOI18N
        lblModo.setText("Relatório de Vendas");

        buttonGroup1.add(rdVend);
        rdVend.setText("Vendas");
        rdVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVendActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdManut);
        rdManut.setText("Manutenções");
        rdManut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdManutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdVend, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdManut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblModo)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdVend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdManut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabVend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabVend);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/nf-32.png"))); // NOI18N
        jButton1.setText("Vizualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        menFiltrar.setText("Filtrar");

        menDat.setText("Data");
        menDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDatActionPerformed(evt);
            }
        });
        menFiltrar.add(menDat);

        jMenuBar.add(menFiltrar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int linha = tabVend.getSelectedRow();
        if (linha != -1 && modoTela == 1) {
            CabNoBean cnb1 = vrt.getLinhas().get((int) tabVend.getValueAt(linha, 0));
            Principal p = new Principal(cnb1);
            this.dispose();
            p.setVisible(true);
        } else {
            CabNoBean cnb1 = vrt.getLinhas().get((int) tabVend.getValueAt(linha, 0));
            NotaOS ntos = new NotaOS(cnb1);
            ntos.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVendActionPerformed
        modoTela = 1;
        lblModo.setText("Relatório de Vendas");
        lblModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/shopping-cart_blue.png")));
        vrt.addListaDeVendas(VendaRelController.read(1));
        tabVend.setModel(vrt);
    }//GEN-LAST:event_rdVendActionPerformed

    private void rdManutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdManutActionPerformed
        modoTela = 2;
        lblModo.setText("OSs com nota");
        lblModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/helpcenter/icons/config-tools-58.png")));
        vrt.addListaDeVendas(VendaRelController.read(2));
    }//GEN-LAST:event_rdManutActionPerformed

    private void menDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDatActionPerformed
        VendaRelData vrd = new VendaRelData(this);
        vrd.setVisible(true);
    }//GEN-LAST:event_menDatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaRel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaRel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblModo;
    private javax.swing.JMenuItem menDat;
    private javax.swing.JMenu menFiltrar;
    private javax.swing.JRadioButton rdManut;
    private javax.swing.JRadioButton rdVend;
    private javax.swing.JTable tabVend;
    // End of variables declaration//GEN-END:variables
}
